fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: Remove unused variables and imports
        language: python
        entry: autoflake
        types: [python]
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: (black) Format Python code
        args: ["--config=pyproject.toml"]
        language: python
        types: [ python ]
        entry: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: (isort) Sorting import statements
        args: ["--settings-path=pyproject.toml"]
        language: python
        types: [python]
        files: \.py$
        entry: isort
